### ISSUE TITLE
新增子节点事件中修改导图的数据导致发生错误

### ISSUE THREAD

**Issue by ajaxpost** [jyoketsu/tree-graph-react#4]
<img width="1091" alt="image" src="https://github.com/jyoketsu/tree-graph-react/assets/74407992/d59c81f4-0571-4055-bbf8-9c0e755c14ca">

通过 按下 TAB 键新增子节点，在监听子节点新增的事件中，修改了导图的数据，导致了这个错误。

这个问题是什么原因导致的？

**Comment by jyoketsu** [comment]
给当前节点新增子节点，要把新的节点的_key添加到当前节点的sortList中，并把当前节点的_key设置到新节点的father字段中。
检查一下是否都做了呢。

**Comment by AnBestActor** [comment]
在新增节点 或更改节点内容 等方法中,修改useState状态就会导致报错~,这个问题应该怎么解决

**Comment by jyoketsu** [comment]
报什么错呢，麻烦具体描述一下。另外，只有受控模式下才能修改节点数据。

**Comment by ajaxpost** [comment]
> 报什么错呢，麻烦具体描述一下。另外，只有受控模式下才能修改节点数据。

就是最开始我发的那个截图，我是这样操作的：

**Comment by ajaxpost** [comment]
> 报什么错呢，麻烦具体描述一下。另外，只有受控模式下才能修改节点数据。

就是最开始发的那个截图，我是这样操作的：

       首先树组件的nodes是一个状态，其次在监听新增子节点的事件中，我修改了这个nodes状态，从而发生了下面的报错。
刚刚说是在事件中修改状态，然而我在任何地方修改这个nodes状态都会发生这种错误。
       然后您说应该在受控模式下修改，那这种与状态绑定的关系就是受控模式。
       
       这是最开始的问题及操作方式，之后我们又搭建了两个测试工程，用的都是同样的代码，同样的操作步骤，但是这三个他们在操作步骤中错误的位置不同。
       只有两个会出现这种错误，最后一个修改状态倒是没有抛出错误。另外安装的版本应该是一样的，这种问题，困扰了我们很久。


       
![image](https://github.com/jyoketsu/tree-graph-react/assets/74407992/f6268d86-5bbb-4eb2-b08d-eaaf92357d27)

**Comment by jyoketsu** [comment]
> > 报什么错呢，麻烦具体描述一下。另外，只有受控模式下才能修改节点数据。
> 
> 就是最开始发的那个截图，我是这样操作的：
> 
> ```
>    首先树组件的nodes是一个状态，其次在监听新增子节点的事件中，我修改了这个nodes状态，从而发生了下面的报错。
> ```
> 
> 刚刚说是在事件中修改状态，然而我在任何地方修改这个nodes状态都会发生这种错误。 然后您说应该在受控模式下修改，那这种与状态绑定的关系就是受控模式。
> 
> ```
>    这是最开始的问题及操作方式，之后我们又搭建了两个测试工程，用的都是同样的代码，同样的操作步骤，但是这三个他们在操作步骤中错误的位置不同。
>    只有两个会出现这种错误，最后一个修改状态倒是没有抛出错误。另外安装的版本应该是一样的，这种问题，困扰了我们很久。
> ```
> 
> ![image](https://user-images.githubusercontent.com/74407992/250823314-f6268d86-5bbb-4eb2-b08d-eaaf92357d27.png)

报错的代码是`nodeMap[selectedId].father === startId`，没有找到`selectedId`的节点。怀疑是新增节点后选中新增节点，但是新增的节点没有放入总的nodes中导致的。
我再贴一下我在项目中新增节点的代码，你参考一下。
```javascript
builder.addCase(
      createBookNode.fulfilled,
      (state, action: PayloadAction<any>) => {
        if (action.payload.statusCode === "200") {
          if (!state.nodeMap) return;
          const addedNode = action.payload.result;
          // 添加节点
          if (action.payload.addType === "child") {
            const selectedNode = state.nodeMap[action.payload.nodeKey];
            if (selectedNode) {
              selectedNode.sortList.push(addedNode._key);
              state.nodeMap[addedNode._key] = addedNode;
            }
          } else if (
            action.payload.addType === "peer" ||
            action.payload.addType === "elder-peer"
          ) {
            // 添加兄弟节点
            let selectedNode = state.nodeMap[action.payload.nodeKey];
            if (selectedNode) {
              let fatherNode = state.nodeMap[selectedNode.father];
              if (fatherNode) {
                let brotherKeys = fatherNode.sortList;
                const index = brotherKeys.indexOf(action.payload.nodeKey);
                brotherKeys.splice(
                  action.payload.addType === "peer" ? index + 1 : index,
                  0,
                  addedNode._key
                );
                fatherNode.sortList = brotherKeys;
                state.nodeMap[addedNode._key] = addedNode;
              }
            }
          }
        } else {
          state.message = {
            text: action.payload.msg,
            severity: "error",
            statusCode: action.payload.statusCode,
          };
        }
      }
    );
```
