### ISSUE TITLE
Vue version?

### ISSUE THREAD

**Issue by iampapagray** [jyoketsu/tree-graph-react#7]
What happened to the vue version of this package? 
No more updates?
No Typescript?

**Comment by jyoketsu** [comment]
Yes, because there is currently no Vue project using this component, I won't update it for now. Alternatively, you can use Veaury in your Vue projects.

**Comment by iampapagray** [comment]
@jyoketsu Is there a way to disable editing nodes? I've added `disabled:true` but im still able to edit.

I would like to use this for view-only. No editing, adding nodes.
What do you suggest?

**Comment by jyoketsu** [comment]
> @jyoketsu Is there a way to disable editing nodes? I've added `disabled:true` but im still able to edit.
> 
> I would like to use this for view-only. No editing, adding nodes. What do you suggest?

use disabled

```javascript
 <Tree
              ref={treeRef}
              startId={rootKey}
              nodes={treeData.data}
              handleClickDot={(node: CNode) => handleClickDot(node)}
              // handleChangeNodeText={(nodeId: string, text: string) =>
              //   handleChangeNodeText(nodeId, text)
              // }
              disabled={readonly}
```
